#!/bin/bash
# Compile
arduino-cli compile --fqbn esp32:esp32:esp32 embedded/ --verbose

# Upload
arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:esp32 embedded/

# Monitor
screen /dev/ttyUSB0 115200
